//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_IJ
    {
        public string IJ_ID { get; set; }
        public string IJ_NO { get; set; }
        public Nullable<System.DateTime> IJ_DD { get; set; }
        public string IJ_REASON { get; set; }
        public string FIX_CST { get; set; }
        public string ACC_NO_D { get; set; }
        public string ACC_NO_C { get; set; }
        public string DEP { get; set; }
        public string VOH_ID { get; set; }
        public string VOH_NO { get; set; }
        public string REF_NO { get; set; }
        public string BAT_NO { get; set; }
        public string MAN_NO { get; set; }
        public string REM { get; set; }
        public string USR { get; set; }
        public string CHK_MAN { get; set; }
        public string PRT_SW { get; set; }
        public string CPY_SW { get; set; }
        public string BIL_NO { get; set; }
        public string BIL_ID { get; set; }
        public Nullable<System.DateTime> CLS_DATE { get; set; }
        public string POS_NO { get; set; }
        public Nullable<decimal> IJID { get; set; }
        public string CAS_NO { get; set; }
        public string BIL_TYPE { get; set; }
        public string CNTT_NO { get; set; }
        public string ACC_NO_SS { get; set; }
        public string ACC_NO_SY { get; set; }
        public string MOB_ID { get; set; }
        public string LOCK_MAN { get; set; }
        public Nullable<System.DateTime> LOCK_DATE { get; set; }
        public Nullable<short> FJ_NUM { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
        public string POS_ID { get; set; }
        public string CUS_NO { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public string PRT_USR { get; set; }
        public string SQ_ID { get; set; }
        public string SQ_NO { get; set; }
        public Nullable<int> SQ_ITM { get; set; }
        public string ISSVS { get; set; }
        public string FROMCB_CALC { get; set; }
        public string JH_SO_NO { get; set; }
        public string TZZG { get; set; }
        public string YG_NO { get; set; }
        public string CANCEL_ID { get; set; }
        public string CUR_ID_IFRS { get; set; }
        public Nullable<decimal> EXC_RTO_IFRS { get; set; }
        public Nullable<System.DateTime> PRT_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DD { get; set; }
        public string MODIFY_MAN { get; set; }
        public string SCAN_ID { get; set; }
        public string SCAN_USR { get; set; }
        public Nullable<System.DateTime> SCAN_DATE { get; set; }
        public string SCAN_USR1 { get; set; }
        public Nullable<System.DateTime> SCAN_DATE1 { get; set; }
        public string GROUP_KEY { get; set; }
        public string IJ_NO_MES { get; set; }
    }
}
