//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_SQ
    {
        public string SQ_NO { get; set; }
        public Nullable<System.DateTime> SQ_DD { get; set; }
        public string DEP { get; set; }
        public string CUS_NO { get; set; }
        public string SAL_NO { get; set; }
        public string PO_NO { get; set; }
        public string INC_ID { get; set; }
        public string REM { get; set; }
        public Nullable<System.DateTime> EST_DD { get; set; }
        public string BIL_ID { get; set; }
        public string USR { get; set; }
        public string CHK_MAN { get; set; }
        public string PRT_SW { get; set; }
        public string CPY_SW { get; set; }
        public string BAT_NO { get; set; }
        public string BIL_NO { get; set; }
        public Nullable<System.DateTime> CLS_DATE { get; set; }
        public string PO_DEP { get; set; }
        public string CLS_ID { get; set; }
        public string BACK_ID { get; set; }
        public string BIL_TYPE { get; set; }
        public string CUR_ID { get; set; }
        public Nullable<decimal> EXC_RTO { get; set; }
        public string SO_NO { get; set; }
        public string MOB_ID { get; set; }
        public string LOCK_MAN { get; set; }
        public Nullable<System.DateTime> LOCK_DATE { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
        public string CAS_NO { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public string SO_ID { get; set; }
        public string PRT_USR { get; set; }
        public string CNTT_NO { get; set; }
        public string CANCEL_ID { get; set; }
        public Nullable<System.DateTime> PRT_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DD { get; set; }
        public string MODIFY_MAN { get; set; }
    }
}
