//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HCTKEntities1 : DbContext
    {
        public DB_HCTKEntities1()
            : base("name=DB_HCTKEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MF_IJ> MF_IJ { get; set; }
        public virtual DbSet<MF_SQ> MF_SQ { get; set; }
        public virtual DbSet<MF_SQ_FX> MF_SQ_FX { get; set; }
        public virtual DbSet<SH_DJ> SH_DJ { get; set; }
        public virtual DbSet<SH_DL> SH_DL { get; set; }
        public virtual DbSet<SH_LIST> SH_LIST { get; set; }
        public virtual DbSet<SH_OTHUSR> SH_OTHUSR { get; set; }
        public virtual DbSet<TF_SHLC> TF_SHLC { get; set; }
    }
}
