//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_DJ
    {
        public string BIL_ID { get; set; }
        public string BIL_NO { get; set; }
        public int BIL_ITM { get; set; }
        public Nullable<System.DateTime> BIL_DD { get; set; }
        public string YN { get; set; }
        public string DEP { get; set; }
        public string USR_MAKE { get; set; }
        public string USR_CHECK { get; set; }
        public string USR_CLOSE { get; set; }
        public string REM { get; set; }
        public string PRE_CHK_MAN { get; set; }
        public string MOB_ID { get; set; }
        public string OT_ID { get; set; }
        public string OT_NO { get; set; }
        public string USR_N { get; set; }
        public Nullable<System.DateTime> SH_DD { get; set; }
        public string OTHUSR { get; set; }
        public Nullable<int> SH_ITM { get; set; }
        public Nullable<int> PRE_SH_ITM { get; set; }
        public Nullable<int> PRE_PRE_SH_ITM { get; set; }
        public string USR_REJIGGER { get; set; }
        public Nullable<System.DateTime> START_DD { get; set; }
        public Nullable<System.DateTime> CHK_DD { get; set; }
        public Nullable<System.DateTime> LAST_DD { get; set; }
        public string OT_ID2 { get; set; }
        public string OT_NO2 { get; set; }
        public string CUS_NO { get; set; }
        public string DEP_BIL { get; set; }
        public string BIL_TYPE { get; set; }
        public string SAL_NO { get; set; }
        public string CUS_OS_NO { get; set; }
        public string BAT_NO { get; set; }
        public string EIP_STS { get; set; }
        public string DTSH_SW { get; set; }
        public string DTSH_NO { get; set; }
        public string VER_NO { get; set; }
        public string NOT_RETURN { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
        public string TYPE_NO { get; set; }
        public string UNSUBMIT { get; set; }
        public string IS_REMODIFY { get; set; }
        public string REM_BIL { get; set; }
    }
}
