//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_DL
    {
        public string USR { get; set; }
        public System.DateTime SQ_DD { get; set; }
        public string BIL_ID { get; set; }
        public string MOB_ID { get; set; }
        public int ITM { get; set; }
        public string USR_DL { get; set; }
        public Nullable<System.DateTime> END_DD { get; set; }
        public string END_ID { get; set; }
        public string REM { get; set; }
        public Nullable<int> SH_ITM { get; set; }
        public string BIL_TYPE { get; set; }
    }
}
