//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_LIST
    {
        public string BIL_ID { get; set; }
        public string BIL_NO { get; set; }
        public int BIL_ITM { get; set; }
        public int ITM { get; set; }
        public string YN { get; set; }
        public string CHK_MAN { get; set; }
        public Nullable<System.DateTime> CHK_DATE { get; set; }
        public string REM { get; set; }
        public Nullable<int> SH_ITM { get; set; }
        public string CHK_MAN_MAIN { get; set; }
        public string YN1 { get; set; }
        public string PRE_TAG { get; set; }
        public string CHK_MAN1 { get; set; }
        public string CHK_MAN_MAIN1 { get; set; }
        public string IS_REMODIFY { get; set; }
    }
}
