//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlbindaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_SHLC
    {
        public string BIL_ID { get; set; }
        public string MOB_ID { get; set; }
        public int ITM { get; set; }
        public string USR { get; set; }
        public string REM { get; set; }
        public string OTHUSR { get; set; }
        public Nullable<short> VALID_TIME { get; set; }
        public Nullable<short> DELAY_TIME { get; set; }
        public string TONEXT { get; set; }
        public string OTH1USR { get; set; }
        public string OTH1USR1 { get; set; }
        public string GROUP_NO { get; set; }
        public string IS_TITLE { get; set; }
        public Nullable<int> SH_ITM { get; set; }
        public string CDT_SQL { get; set; }
    }
}
